### ISSUE TITLE
numpy issues on MAC installation

### ISSUE THREAD

**Issue by itsjesshewitt** [chychkan/DeepFaceLab_MacOS#12]
Hi there!

I just downloaded all the content via your instructions for deepfacelab for mac, and when I try running the second script '2_extract_images_from_video_data_src.sh' I get the following error:

`Traceback (most recent call last):
  File "/Users/MYUSERNAME/DeepFaceLab_MacOS/.dfl/DeepFaceLab/main.py", line 6, in <module>
    from core.leras import nn
  File "/Users/MYUSERNAME/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/Users/MYUSERNAME/DeepFaceLab_MacOS/.dfl/DeepFaceLab/core/leras/nn.py", line 25, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'`

However i've also tried using pip3 install numpy, and brew install numpy, both of which worked, and i've even checked the version of numpy - but I still get the 'no module named numpy' error when i run the second script.  Any help for this?

Thanks!

**Comment by chychkan** [comment]
Hi @itsjesshewitt! Error message like that most likely means that the execution of the `./scripts/0_setup.sh` was not successful. Could you please try running it again and share it's full output as well as what is the Python version you're using (you can find your Python version by executing command `python -V`).
