### ISSUE TITLE
Issue installing DeepFaceLab_MacOS on Python 3.10

### ISSUE THREAD

**Issue by samuelemirotta** [chychkan/DeepFaceLab_MacOS#47]
Hi,
here's the issue i get when i launch 0_setup.sh file:

Using requirements.txt
Collecting numpy==1.19.5
  Using cached numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement opencv-contrib-python-headless==4.1.2.30 (from versions: 3.4.11.45, 3.4.13.47, 3.4.14.51, 3.4.15.55, 3.4.16.57, 4.4.0.46, 4.5.1.48, 4.5.2.52, 4.5.3.56, 4.5.4.58)
ERROR: No matching distribution found for opencv-contrib-python-headless==4.1.2.30

**Comment by chychkan** [comment]
@samuelemirotta what version of Python are you using?

**Comment by samuelemirotta** [comment]
3.10

**Comment by chychkan** [comment]
@samuelemirotta 
Python 3.10 is not supported yet. DeepFaceLab uses `scipy` and currently there's no released `scipy` version compatible with Python 3.10.

To be able to run DeepFaceLab you need to switch to Python 3.9. To have multiple Python versions and easily switch between them, I would recommend https://github.com/pyenv/pyenv. I use it myself.

**Comment by chychkan** [comment]
Fixed by https://github.com/chychkan/DeepFaceLab_MacOS/pull/49
