### ISSUE TITLE
Use python3.7

### ISSUE THREAD

**Issue by acheong08** [chychkan/DeepFaceLab_MacOS#6]
Errors when using python3.9

**Comment by smm0864** [comment]
when running the install script getting the following error (python 3.9)

```
Collecting numpy==1.17.0
  Downloading numpy-1.17.0.zip (6.5 MB)
     |████████████████████████████████| 6.5 MB 1.5 MB/s
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.0.25
ERROR: No matching distribution found for opencv-python==4.1.0.25
```
trying to install opencv manually results in similar error:

```
$pip3 install opencv-python==4.1.2.30
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48)
ERROR: No matching distribution found for opencv-python==4.1.2.30
```

**Comment by LordLommel** [comment]
Downgrade to Python 3.7 did not work fro me.

**Comment by chychkan** [comment]
Hi everyone! I added support for Python `3.7` and `3.8` and I'm working on support for `3.9`.
Make sure you drop the `.dfl/env/` directory and re-run the `./scripts/0_setup.sh` when you switch to a different Python version.

**Comment by chychkan** [comment]
Now should work for Python 3.9 too (added in https://github.com/chychkan/DeepFaceLab_MacOS/pull/16)
