### ISSUE TITLE
The script list is not completed

### ISSUE THREAD

**Issue by hongkongfake** [chychkan/DeepFaceLab_MacOS#65]
Is it possible to include the rest of the scripts? Like Xseg for dst and training etc.

**Comment by chychkan** [comment]
@hongkongfake could you please be more specific. The repo already has the script to run XSeg editor (try `./scripts/xseg.sh`). What other missing scripts do you mean?
Also, contributions are welcome, so please feel free to open a PR.

**Comment by hongkongfake** [comment]
> @hongkongfake could you please be more specific. The repo already has the script to run XSeg editor (try `./scripts/xseg.sh`). What other missing scripts do you mean?
> Also, contributions are welcome, so please feel free to open a PR.

**Comment by hongkongfake** [comment]
Yes it is but it only directs to "Aligned src", in the original script folder there are a list of Xseg-related scripts:

5.XSeg) data_dst mask for XSeg trainer - edit - label tool to mark DST faces with XSeg polygons.
5.XSeg) data_dst mask for XSeg trainer - fetch - makes a copy of labeled DST faces to folder "aligned_xseg".
5.XSeg) data_dst mask for XSeg trainer - remove - removes labels from your DST faces.
5.XSeg) data_src mask for XSeg trainer - edit - label tool to mark SRC faces with XSeg polygons.
5.XSeg) data_src mask for XSeg trainer - fetch - makes a copy of labeled SRC faces to folder "aligned_xseg".
5.XSeg) data_src mask for XSeg trainer - remove - removes labels from your SRC faces.
XSeg) train.bat - starts training of the XSeg model.
5.XSeg.optional) trained mask for data_dst - apply - generates and applies XSeg masks to your DST faces.
5.XSeg.optional) trained mask for data_dst - remove - removes XSeg masks and restores default FF like DST masks.
5.XSeg.optional) trained mask for data_src - apply - generates and applies XSeg masks to your DST faces.
5.XSeg.optional) trained mask for data_src - remove - removes XSeg masks and restores default FF like SRC masks.

I'm sorry since I don't know coding, even I want to add the scripts but I just don't know how to do so, therefore I have to raise the issue here.

**Comment by chychkan** [comment]
Resolved by https://github.com/chychkan/DeepFaceLab_MacOS/pull/76
